### ISSUE TITLE
Dropping off the world map even at 30x

### ISSUE THREAD

**Issue by InconsolableCellist** [TheNewBob/TediousTravel#22]
When it's dark and snowing I keep dropping off the edge of the world when fast traveling, even at 30x. Can the mod detect this condition and bring you back to a safe location? Or have a manual rescue button so that I don't have to load? As it is I can barely make it across Daggerfall, let alone to Wayrest or Sentinel.

**Comment by TheNewBob** [comment]
30 times on horseback is pretty fast if you have hungry mods installed and don't have a very powerful machine, *especially* when weather effects are active.
https://github.com/TheNewBob/TediousTravel/tree/c1df567ec1c9eb3bd4e0e3a47b82443a7f333975 deactivates weather effect while fast travelling, so that should help with that, but I don't see what else I can optimise.
